//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogo
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.categoria11 = new HashSet<categoria>();
            this.productoes = new HashSet<producto>();
        }
    
        public int id_categoria { get; set; }
        public string categoria1 { get; set; }
        public Nullable<int> categoria_padre { get; set; }
    
        public virtual ICollection<categoria> categoria11 { get; set; }
        public virtual categoria categoria2 { get; set; }
        public virtual ICollection<producto> productoes { get; set; }
    }
}
